services:
     testapi:
       build:
         context: .
         dockerfile: Dockerfile
       ports:
         - "8080:80"
       environment:
         - ASPNETCORE_ENVIRONMENT=Development
       container_name: c_testapi